# -*- coding: utf-8 -*-
"""Data Standardization1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yf0VjubHkyDO11a17IPq13GfTN564jaT
"""

import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

dataset = sklearn.datasets.load_breast_cancer()

print(dataset)

df = pd.DataFrame(dataset.data, columns= dataset.feature_names)

df.head()

df.shape

X = df
Y = dataset.target

print(X)

print(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=3)

print(X.shape, X_train.shape, X_test.shape)

print(dataset.data.std())

scaler = StandardScaler()

scaler.fit(X_train)

X_train_standardized = scaler.transform(X_train)

print(X_train_standardized)

X_test_standardized = scaler.transform(X_test)

print(X_train_standardized.std())

